### ISSUE TITLE
Icon missing on steam game list [BUG] 

### ISSUE THREAD

**Issue by FDuplat** [stevealexandre/UWPHook#7]
My games are showing this little icon on the steam list instead of the games icon, game icons on streamgrid are working properly

![image](https://user-images.githubusercontent.com/105004950/195655976-4c3d2e98-bdb7-4196-9c87-18ce5800059b.png)
![image](https://user-images.githubusercontent.com/105004950/195655998-6453dbb6-ea5b-4661-831d-c8cfa318177f.png)

**Comment by stevealexandre** [comment]
Hey,

Thanks for your issue. I will take a look before the end of the week.
The icon on the uwphook grid are pulled from the steam api but from the game directly which is sometimes better.
However it's pretty weird that you get the same game icon for the 3 games.

Will keep you in touch.

**Comment by stevealexandre** [comment]
Hello @XmutanoX,

Find below the last release with the fix. Enjoy !
https://github.com/stevealexandre/UWPHook/releases/tag/2.15.1

Let me know if the issue is fixed on your side to close the issue.

**Comment by FDuplat** [comment]
issue is fixed! Thanks for the help
